### ISSUE TITLE
随身末影箱功能无法启用

### ISSUE THREAD

**Issue by YuYue-Amatsuki** [HowieHz/Points#6]
插件版本：0.2.7
服务端及服务端版本：Leaves-1.20.4（为paper下游服务端）
输入插件的随身末影箱指令后提示未启用该功能，但实际在配置文件内已启用，并在luckperms配置相关权限

配置文件如下
```yaml
enderchest:
  # 随身末影箱
  enable: true  # 是否启用enderchest随身末影箱
  permission:
    self: # enderchest对象为玩家自己
      enable: true  # 此项是否需要权限才能使用
      node: points.command.enderchest.self
    other: # enderchest对象为其他玩家
      enable: true  # 此项是否需要权限才能使用
      node-other-player: points.command.enderchest.other  # 其他玩家
      node-target-player: points.command.enderchest.other.%s  # 指定玩家 %s为玩家名的占位符
```
Luckperms已配置对应权限
![IMG_20240826_232305.jpg](https://github.com/user-attachments/assets/174a29b4-545c-4599-9c42-c7598c90ad6e)

输入指令提示未启用功能
![1000027914.gif](https://github.com/user-attachments/assets/2a692650-738a-4c33-bc05-6999fc19265a)
